name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Xcode Version
      run: ls /Applications | grep Xcode 
      run: ls /Applications | grep Xcode | xargs -I {} /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" /Applications/{}/Contents/Info.plist
